CREATE TABLE public_interaction
(
    interaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    citezen_name   VARCHAR(50),
    citezen_email  VARCHAR(30),
    citezen_phone  INTEGER,
    case_id        BIGINT,
    CONSTRAINT pk_public_interaction PRIMARY KEY (interaction_id)
);

ALTER TABLE public_interaction
    ADD CONSTRAINT uc_public_interaction_case UNIQUE (case_id);

ALTER TABLE public_interaction
    ADD CONSTRAINT FK_PUBLIC_INTERACTION_ON_CASE FOREIGN KEY (case_id) REFERENCES case_files (case_id);