CREATE TABLE case_notes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id BIGINT                                  NOT NULL,
    content TEXT                                    NOT NULL,
    user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_case_notes PRIMARY KEY (id)
);

CREATE TABLE case_version
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    case_id        BIGINT                                  NOT NULL,
    version_data   TEXT                                    NOT NULL,
    version_number INTEGER                                 NOT NULL,
    CONSTRAINT pk_case_version PRIMARY KEY (id)
);

ALTER TABLE case_notes
    ADD CONSTRAINT FK_CASE_NOTES_ON_CASE FOREIGN KEY (case_id) REFERENCES case_files (case_id);

ALTER TABLE case_notes
    ADD CONSTRAINT FK_CASE_NOTES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE case_version
    ADD CONSTRAINT FK_CASE_VERSION_ON_CASE FOREIGN KEY (case_id) REFERENCES case_files (case_id);