CREATE TABLE agents_chats
(
    agent_id BIGINT NOT NULL,
    chat_id  BIGINT NOT NULL
);

CREATE TABLE chats
(
    chat_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_type      VARCHAR(255)                            NOT NULL,
    created_at     BYTEA                                   NOT NULL,
    reason         VARCHAR(255),
    scheduled_date date,
    scheduled_time time WITHOUT TIME ZONE,
    status         VARCHAR(255),
    personal_code  VARCHAR(255),
    CONSTRAINT pk_chats PRIMARY KEY (chat_id)
);

CREATE TABLE messages
(
    message_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_text VARCHAR(255)                            NOT NULL,
    sent_at      time WITHOUT TIME ZONE                  NOT NULL,
    read_at      time WITHOUT TIME ZONE                  NOT NULL,
    file_path    VARCHAR(255),
    chat_id      BIGINT,
    agent_id     BIGINT,
    CONSTRAINT pk_messages PRIMARY KEY (message_id)
);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_AGENT FOREIGN KEY (agent_id) REFERENCES agents (agent_id);

ALTER TABLE messages
    ADD CONSTRAINT FK_MESSAGES_ON_CHAT FOREIGN KEY (chat_id) REFERENCES chats (chat_id);

ALTER TABLE agents_chats
    ADD CONSTRAINT fk_agecha_on_agents FOREIGN KEY (agent_id) REFERENCES agents (agent_id);

ALTER TABLE agents_chats
    ADD CONSTRAINT fk_agecha_on_chats FOREIGN KEY (chat_id) REFERENCES chats (chat_id);